import type { Rules } from "../types";

export const DEFAULT_RULES: Rules = {
  inviteDaysBefore: 14,
  chaserHoursBefore: 48,
  closureHoursBefore: 4,
  autoFulfillment: true,
  requirePurchased: true,
  blindBids: true,
  maxUpgradesPerFlight: 0,
  multiplierPlatinum: 10,
  multiplierGold: 5,
  multiplierSilver: 3,
  minBcUltraShort: 93,
  minBcShort: 118,
  minBcMedium: 262,
  minBcLong: 500,
  minBcUltraLong: 569,
  minExitShort: 8,
  minExitMedium: 32,
  minExitLong: 35,
  minSeatBlockShort: 8,
  minSeatBlockMedium: 32,
  minSeatBlockLong: 35,
  channels: { email: true, mmb: true, app: true, web: true, webcheckin: true, pushNotif: true },
  paymentMethods: { visa: true, mastercard: true, amex: true, jcb: false, diners: false },
  use3ds: false,
  continuousPricing: true,
  crossAirlineUpgrades: false,
  payWithPoints: false,
  seatBlocker: true,
};
