import type { Airport, Bid, Channel, City, Country, Flight, Passenger } from "./types";

export const COUNTRIES_DATA: Country[] = [
  { id: "uz", name: { en: "Uzbekistan", ru: "Узбекистан" } },
  { id: "tr", name: { en: "Turkey", ru: "Турция" } },
  { id: "ae", name: { en: "United Arab Emirates", ru: "ОАЭ" } },
  { id: "ru", name: { en: "Russia", ru: "Россия" } },
  { id: "de", name: { en: "Germany", ru: "Германия" } },
  { id: "cn", name: { en: "China", ru: "Китай" } },
  { id: "kr", name: { en: "South Korea", ru: "Южная Корея" } },
  { id: "gb", name: { en: "United Kingdom", ru: "Великобритания" } },
  { id: "kz", name: { en: "Kazakhstan", ru: "Казахстан" } },
];

export const CITIES_DATA: City[] = [
  {
    id: "tashkent",
    name: { en: "Tashkent", ru: "Ташкент" },
    countryId: "uz",
    timezone: "Asia/Tashkent",
  },
  {
    id: "istanbul",
    name: { en: "Istanbul", ru: "Стамбул" },
    countryId: "tr",
    timezone: "Europe/Istanbul",
  },
  { id: "dubai", name: { en: "Dubai", ru: "Дубай" }, countryId: "ae", timezone: "Asia/Dubai" },
  {
    id: "moscow",
    name: { en: "Moscow", ru: "Москва" },
    countryId: "ru",
    timezone: "Europe/Moscow",
  },
  {
    id: "frankfurt",
    name: { en: "Frankfurt", ru: "Франкфурт" },
    countryId: "de",
    timezone: "Europe/Berlin",
  },
  {
    id: "beijing",
    name: { en: "Beijing", ru: "Пекин" },
    countryId: "cn",
    timezone: "Asia/Shanghai",
  },
  { id: "seoul", name: { en: "Seoul", ru: "Сеул" }, countryId: "kr", timezone: "Asia/Seoul" },
  {
    id: "london",
    name: { en: "London", ru: "Лондон" },
    countryId: "gb",
    timezone: "Europe/London",
  },
  {
    id: "almaty",
    name: { en: "Almaty", ru: "Алматы" },
    countryId: "kz",
    timezone: "Asia/Almaty",
  },
];

export const AIRPORTS_DATA: Airport[] = [
  {
    id: "TAS",
    name: { en: "Tashkent International Airport", ru: "Международный аэропорт Ташкент" },
    cityId: "tashkent",
  },
  {
    id: "IST",
    name: { en: "Istanbul Airport", ru: "Аэропорт Стамбул" },
    cityId: "istanbul",
  },
  {
    id: "DXB",
    name: { en: "Dubai International Airport", ru: "Международный аэропорт Дубай" },
    cityId: "dubai",
  },
  {
    id: "MOW",
    name: { en: "Moscow Sheremetyevo Airport", ru: "Шереметьево" },
    cityId: "moscow",
  },
  {
    id: "FRA",
    name: { en: "Frankfurt Airport", ru: "Аэропорт Франкфурт" },
    cityId: "frankfurt",
  },
  {
    id: "PEK",
    name: { en: "Beijing Capital International Airport", ru: "Пекин Столичный" },
    cityId: "beijing",
  },
  {
    id: "ICN",
    name: { en: "Incheon International Airport", ru: "Аэропорт Инчхон" },
    cityId: "seoul",
  },
  {
    id: "LHR",
    name: { en: "London Heathrow Airport", ru: "Хитроу" },
    cityId: "london",
  },
  {
    id: "ALA",
    name: { en: "Almaty International Airport", ru: "Международный аэропорт Алматы" },
    cityId: "almaty",
  },
];

export const PASSENGERS_DATA: Passenger[] = [
  { id: "p001", name: "Иванов А.П.", tier: "Platinum", initials: "ИА" },
  { id: "p002", name: "Ли Вэй", tier: "Gold", initials: "ЛВ" },
  { id: "p003", name: "Петрова М.С.", tier: "Silver", initials: "ПМ" },
  { id: "p004", name: "Smith J.", tier: "Standard", initials: "SJ" },
  { id: "p005", name: "Karimov B.", tier: "Platinum", initials: "KB" },
  { id: "p006", name: "Ahmadov F.", tier: "Standard", initials: "AF" },
  { id: "p007", name: "Brown T.", tier: "Gold", initials: "BT" },
  { id: "p008", name: "Назаров О.", tier: "Standard", initials: "НО" },
  { id: "p009", name: "Юсупова Д.", tier: "Silver", initials: "ЮД" },
  { id: "p010", name: "Kim S.", tier: "Gold", initials: "KS" },
  { id: "p011", name: "Tan W.", tier: "Gold", initials: "TW" },
  { id: "p012", name: "Орлов И.", tier: "Standard", initials: "ОИ" },
  { id: "p013", name: "Patel R.", tier: "Silver", initials: "PR" },
  { id: "p014", name: "Khan A.", tier: "Standard", initials: "KA" },
  { id: "p015", name: "Соколов В.", tier: "Platinum", initials: "СВ" },
  { id: "p016", name: "Юлдашев Б.", tier: "Gold", initials: "ЮБ" },
  { id: "p017", name: "Ким Д.", tier: "Standard", initials: "КД" },
  { id: "p018", name: "Морозова Е.", tier: "Silver", initials: "МЕ" },
  { id: "p019", name: "Müller K.", tier: "Gold", initials: "MK" },
  { id: "p020", name: "Schmidt L.", tier: "Standard", initials: "SL" },
  { id: "p021", name: "Усманов Р.", tier: "Silver", initials: "УР" },
  { id: "p022", name: "Wang J.", tier: "Platinum", initials: "WJ" },
  { id: "p023", name: "Liu Y.", tier: "Gold", initials: "LY" },
  { id: "p024", name: "Zhang H.", tier: "Standard", initials: "ZH" },
  { id: "p025", name: "Chen X.", tier: "Silver", initials: "CX" },
  { id: "p026", name: "Park J.", tier: "Gold", initials: "PJ" },
  { id: "p027", name: "Lee H.", tier: "Platinum", initials: "LH" },
  { id: "p028", name: "Choi S.", tier: "Standard", initials: "CS" },
  { id: "p029", name: "Ким Н.", tier: "Silver", initials: "КН" },
  { id: "p030", name: "Yoon T.", tier: "Standard", initials: "YT" },
  { id: "p031", name: "Williams P.", tier: "Platinum", initials: "WP" },
  { id: "p032", name: "Davies M.", tier: "Gold", initials: "DM" },
  { id: "p033", name: "Aliev R.", tier: "Gold", initials: "AR" },
  { id: "p034", name: "Назарбаев А.", tier: "Standard", initials: "НА" },
  { id: "p035", name: "Tolegen B.", tier: "Silver", initials: "TB" },
  { id: "p036", name: "Khan A.", tier: "Gold", initials: "KA" },
  { id: "p037", name: "Park J.", tier: "Standard", initials: "PJ" },
  { id: "p038", name: "Орлов В.", tier: "Silver", initials: "ОВ" },
  { id: "p039", name: "Müller K.", tier: "Standard", initials: "MK" },
  { id: "p040", name: "Сидорова Е.", tier: "Gold", initials: "СЕ" },
  { id: "p041", name: "Tanaka R.", tier: "Standard", initials: "TR" },
  { id: "p042", name: "Назаров Б.", tier: "Silver", initials: "НБ" },
  { id: "p043", name: "Garcia L.", tier: "Standard", initials: "GL" },
  { id: "p044", name: "Choi H.", tier: "Standard", initials: "CH" },
  { id: "p045", name: "Романов И.", tier: "Silver", initials: "РИ" },
  { id: "p046", name: "Fischer T.", tier: "Standard", initials: "FT" },
  { id: "p047", name: "Алиев Р.", tier: "Standard", initials: "АР" },
  { id: "p048", name: "Singh P.", tier: "Standard", initials: "SP" },
  { id: "p049", name: "Чен Ю.", tier: "Standard", initials: "ЧЮ" },
  { id: "p050", name: "Ким А.", tier: "Gold", initials: "КА" },
  { id: "p051", name: "Brown D.", tier: "Standard", initials: "BD" },
  { id: "p052", name: "Юлдашев Б.", tier: "Silver", initials: "ЮБ" },
  { id: "p053", name: "Назарова Г.", tier: "Gold", initials: "НГ" },
  { id: "p054", name: "Iqbal S.", tier: "Standard", initials: "IS" },
  { id: "p055", name: "Каримова З.", tier: "Standard", initials: "КЗ" },
  { id: "p056", name: "Rahimi K.", tier: "Silver", initials: "RK" },
  { id: "p057", name: "Соколов Д.", tier: "Standard", initials: "СД" },
  { id: "p058", name: "Yamamoto T.", tier: "Standard", initials: "YT" },
  { id: "p059", name: "Эргашев А.", tier: "Gold", initials: "ЭА" },
  { id: "p060", name: "Lopez M.", tier: "Standard", initials: "LM" },
  { id: "p061", name: "Тимуров К.", tier: "Standard", initials: "ТК" },
  { id: "p062", name: "Wang L.", tier: "Silver", initials: "WL" },
  { id: "p063", name: "Захаров П.", tier: "Standard", initials: "ЗП" },
  { id: "p064", name: "Ahmed F.", tier: "Standard", initials: "AF" },
  { id: "p065", name: "Юсупов Т.", tier: "Gold", initials: "ЮТ" },
  { id: "p066", name: "Novak J.", tier: "Standard", initials: "NJ" },
  { id: "p067", name: "Габидуллина М.", tier: "Standard", initials: "ГМ" },
  { id: "p068", name: "Bekov S.", tier: "Silver", initials: "BS" },
  { id: "p069", name: "Petrov K.", tier: "Standard", initials: "PK" },
  { id: "p070", name: "Хасанов Н.", tier: "Standard", initials: "ХН" },
];

export const FLIGHTS_DATA: Flight[] = [
  {
    id: "HY 602",
    fromAirportId: "TAS",
    toAirportId: "IST",
    depAt: "2026-06-15T08:45:00Z",
    arrAt: "2026-06-15T14:20:00Z",
    aircraft: "A321",
    bcFree: 2,
    bcTotal: 16,
    status: "active",
    haul: "medium",
  },
  {
    id: "HY 814",
    fromAirportId: "TAS",
    toAirportId: "DXB",
    depAt: "2026-06-15T14:30:00Z",
    arrAt: "2026-06-15T19:15:00Z",
    aircraft: "B787",
    bcFree: 8,
    bcTotal: 24,
    status: "active",
    haul: "medium",
  },
  {
    id: "HY 233",
    fromAirportId: "TAS",
    toAirportId: "MOW",
    depAt: "2026-06-15T11:15:00Z",
    arrAt: "2026-06-15T14:30:00Z",
    aircraft: "A320",
    bcFree: 0,
    bcTotal: 8,
    status: "sold",
    haul: "short",
  },
  {
    id: "HY 177",
    fromAirportId: "TAS",
    toAirportId: "FRA",
    depAt: "2026-06-16T06:00:00Z",
    arrAt: "2026-06-16T13:45:00Z",
    aircraft: "B767",
    bcFree: 14,
    bcTotal: 20,
    status: "upcoming",
    haul: "long",
  },
  {
    id: "HY 409",
    fromAirportId: "TAS",
    toAirportId: "PEK",
    depAt: "2026-06-16T09:20:00Z",
    arrAt: "2026-06-16T14:50:00Z",
    aircraft: "A330",
    bcFree: 6,
    bcTotal: 18,
    status: "active",
    haul: "medium",
  },
  {
    id: "HY 551",
    fromAirportId: "TAS",
    toAirportId: "ICN",
    depAt: "2026-06-16T13:00:00Z",
    arrAt: "2026-06-16T19:15:00Z",
    aircraft: "B787",
    bcFree: 3,
    bcTotal: 20,
    status: "active",
    haul: "long",
  },
  {
    id: "HY 088",
    fromAirportId: "TAS",
    toAirportId: "LHR",
    depAt: "2026-06-17T00:30:00Z",
    arrAt: "2026-06-17T09:20:00Z",
    aircraft: "B767",
    bcFree: 10,
    bcTotal: 16,
    status: "upcoming",
    haul: "ultra",
  },
  {
    id: "HY 312",
    fromAirportId: "TAS",
    toAirportId: "ALA",
    depAt: "2026-06-15T16:45:00Z",
    arrAt: "2026-06-15T17:50:00Z",
    aircraft: "A319",
    bcFree: 4,
    bcTotal: 8,
    status: "active",
    haul: "ultra-short",
  },
];

// Hand-authored seed. HY 602 keeps the curated 10 bids that drive the detail UI and
// auto-select tests (top weighted: id 1 = 682, id 4 = 580). Other flights get a small
// realistic spread so list-view aggregates aren't all zero.

type ExitRowSeed = {
  id: number;
  passengerId: Passenger["id"];
  bid: number;
  channel: Channel;
  time: string;
};

function exitRowBids(flightId: Flight["id"], rows: ExitRowSeed[]): Bid[] {
  return rows.map((r) => ({
    flightId,
    id: r.id,
    product: "exitRows",
    passengerId: r.passengerId,
    bid: r.bid,
    mult: 1.0,
    channel: r.channel,
    time: r.time,
    state: "pending",
  }));
}

export const SEED_BIDS: Bid[] = [
  // HY 602 (bcFree 2 — auto-select picks ids 1 and 4)
  {
    flightId: "HY 602",
    id: 1,
    product: "businessClass",
    passengerId: "p001",
    bid: 620,
    mult: 1.1,
    channel: "Email",
    time: "09:14",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 2,
    product: "businessClass",
    passengerId: "p002",
    bid: 520,
    mult: 1.05,
    channel: "App",
    time: "13:07",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 3,
    product: "businessClass",
    passengerId: "p003",
    bid: 490,
    mult: 1.03,
    channel: "Email",
    time: "10:21",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 4,
    product: "businessClass",
    passengerId: "p004",
    bid: 580,
    mult: 1.0,
    channel: "MMB",
    time: "11:32",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 5,
    product: "businessClass",
    passengerId: "p005",
    bid: 400,
    mult: 1.1,
    channel: "Web",
    time: "08:55",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 6,
    product: "businessClass",
    passengerId: "p006",
    bid: 470,
    mult: 1.0,
    channel: "Email",
    time: "14:45",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 7,
    product: "businessClass",
    passengerId: "p007",
    bid: 380,
    mult: 1.05,
    channel: "MMB",
    time: "07:30",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 8,
    product: "businessClass",
    passengerId: "p008",
    bid: 310,
    mult: 1.0,
    channel: "Web",
    time: "16:02",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 9,
    product: "businessClass",
    passengerId: "p009",
    bid: 345,
    mult: 1.03,
    channel: "Email",
    time: "15:18",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 10,
    product: "businessClass",
    passengerId: "p010",
    bid: 430,
    mult: 1.05,
    channel: "App",
    time: "12:00",
    state: "pending",
  },

  // HY 814
  {
    flightId: "HY 814",
    id: 1,
    product: "businessClass",
    passengerId: "p011",
    bid: 480,
    mult: 1.05,
    channel: "App",
    time: "09:20",
    state: "pending",
  },
  {
    flightId: "HY 814",
    id: 2,
    product: "businessClass",
    passengerId: "p012",
    bid: 410,
    mult: 1.0,
    channel: "Web",
    time: "10:05",
    state: "pending",
  },
  {
    flightId: "HY 814",
    id: 3,
    product: "businessClass",
    passengerId: "p013",
    bid: 360,
    mult: 1.03,
    channel: "Email",
    time: "11:40",
    state: "pending",
  },
  {
    flightId: "HY 814",
    id: 4,
    product: "businessClass",
    passengerId: "p014",
    bid: 300,
    mult: 1.0,
    channel: "MMB",
    time: "13:12",
    state: "pending",
  },

  // HY 233 (sold)
  {
    flightId: "HY 233",
    id: 1,
    product: "businessClass",
    passengerId: "p015",
    bid: 390,
    mult: 1.1,
    channel: "Email",
    time: "07:45",
    state: "pending",
  },
  {
    flightId: "HY 233",
    id: 2,
    product: "businessClass",
    passengerId: "p016",
    bid: 350,
    mult: 1.05,
    channel: "App",
    time: "08:10",
    state: "pending",
  },
  {
    flightId: "HY 233",
    id: 3,
    product: "businessClass",
    passengerId: "p017",
    bid: 280,
    mult: 1.0,
    channel: "Web",
    time: "09:30",
    state: "pending",
  },
  {
    flightId: "HY 233",
    id: 4,
    product: "businessClass",
    passengerId: "p018",
    bid: 260,
    mult: 1.03,
    channel: "Email",
    time: "10:15",
    state: "pending",
  },

  // HY 177
  {
    flightId: "HY 177",
    id: 1,
    product: "businessClass",
    passengerId: "p019",
    bid: 550,
    mult: 1.05,
    channel: "App",
    time: "06:20",
    state: "pending",
  },
  {
    flightId: "HY 177",
    id: 2,
    product: "businessClass",
    passengerId: "p020",
    bid: 480,
    mult: 1.0,
    channel: "Web",
    time: "07:50",
    state: "pending",
  },
  {
    flightId: "HY 177",
    id: 3,
    product: "businessClass",
    passengerId: "p021",
    bid: 420,
    mult: 1.03,
    channel: "Email",
    time: "09:00",
    state: "pending",
  },

  // HY 409
  {
    flightId: "HY 409",
    id: 1,
    product: "businessClass",
    passengerId: "p022",
    bid: 510,
    mult: 1.1,
    channel: "App",
    time: "08:00",
    state: "pending",
  },
  {
    flightId: "HY 409",
    id: 2,
    product: "businessClass",
    passengerId: "p023",
    bid: 460,
    mult: 1.05,
    channel: "Email",
    time: "08:35",
    state: "pending",
  },
  {
    flightId: "HY 409",
    id: 3,
    product: "businessClass",
    passengerId: "p024",
    bid: 380,
    mult: 1.0,
    channel: "MMB",
    time: "09:15",
    state: "pending",
  },
  {
    flightId: "HY 409",
    id: 4,
    product: "businessClass",
    passengerId: "p025",
    bid: 340,
    mult: 1.03,
    channel: "Web",
    time: "10:00",
    state: "pending",
  },

  // HY 551
  {
    flightId: "HY 551",
    id: 1,
    product: "businessClass",
    passengerId: "p026",
    bid: 540,
    mult: 1.05,
    channel: "App",
    time: "11:00",
    state: "pending",
  },
  {
    flightId: "HY 551",
    id: 2,
    product: "businessClass",
    passengerId: "p027",
    bid: 500,
    mult: 1.1,
    channel: "Email",
    time: "11:30",
    state: "pending",
  },
  {
    flightId: "HY 551",
    id: 3,
    product: "businessClass",
    passengerId: "p028",
    bid: 420,
    mult: 1.0,
    channel: "MMB",
    time: "12:10",
    state: "pending",
  },
  {
    flightId: "HY 551",
    id: 4,
    product: "businessClass",
    passengerId: "p029",
    bid: 380,
    mult: 1.03,
    channel: "Web",
    time: "12:45",
    state: "pending",
  },
  {
    flightId: "HY 551",
    id: 5,
    product: "businessClass",
    passengerId: "p030",
    bid: 320,
    mult: 1.0,
    channel: "App",
    time: "13:00",
    state: "pending",
  },

  // HY 088
  {
    flightId: "HY 088",
    id: 1,
    product: "businessClass",
    passengerId: "p031",
    bid: 600,
    mult: 1.1,
    channel: "Email",
    time: "22:30",
    state: "pending",
  },
  {
    flightId: "HY 088",
    id: 2,
    product: "businessClass",
    passengerId: "p032",
    bid: 540,
    mult: 1.05,
    channel: "App",
    time: "23:10",
    state: "pending",
  },

  // HY 312 (ultra-short)
  {
    flightId: "HY 312",
    id: 1,
    product: "businessClass",
    passengerId: "p033",
    bid: 95,
    mult: 1.05,
    channel: "App",
    time: "15:30",
    state: "pending",
  },
  {
    flightId: "HY 312",
    id: 2,
    product: "businessClass",
    passengerId: "p034",
    bid: 80,
    mult: 1.0,
    channel: "Web",
    time: "16:00",
    state: "pending",
  },
  {
    flightId: "HY 312",
    id: 3,
    product: "businessClass",
    passengerId: "p035",
    bid: 70,
    mult: 1.03,
    channel: "Email",
    time: "16:15",
    state: "pending",
  },
  // ---- Exit-row bids ($32–$85) ----
  // HY 602 (14 — drives the detail page chart)
  ...exitRowBids("HY 602", [
    { id: 11, passengerId: "p036", bid: 82, channel: "App", time: "07:42" },
    { id: 12, passengerId: "p037", bid: 78, channel: "Web", time: "08:11" },
    { id: 13, passengerId: "p038", bid: 75, channel: "Email", time: "09:03" },
    { id: 14, passengerId: "p039", bid: 72, channel: "MMB", time: "09:48" },
    { id: 15, passengerId: "p040", bid: 68, channel: "App", time: "10:30" },
    { id: 16, passengerId: "p041", bid: 64, channel: "Web", time: "11:05" },
    { id: 17, passengerId: "p042", bid: 62, channel: "Email", time: "11:42" },
    { id: 18, passengerId: "p043", bid: 60, channel: "App", time: "12:15" },
    { id: 19, passengerId: "p044", bid: 58, channel: "MMB", time: "13:00" },
    { id: 20, passengerId: "p045", bid: 52, channel: "Web", time: "13:38" },
    { id: 21, passengerId: "p046", bid: 48, channel: "App", time: "14:20" },
    { id: 22, passengerId: "p047", bid: 42, channel: "Email", time: "15:05" },
    { id: 23, passengerId: "p048", bid: 38, channel: "Web", time: "15:44" },
    { id: 24, passengerId: "p049", bid: 32, channel: "MMB", time: "16:22" },
  ]),
  ...exitRowBids("HY 814", [
    { id: 5, passengerId: "p050", bid: 80, channel: "App", time: "10:11" },
    { id: 6, passengerId: "p051", bid: 65, channel: "Web", time: "11:48" },
    { id: 7, passengerId: "p052", bid: 50, channel: "Email", time: "12:30" },
  ]),
  ...exitRowBids("HY 233", [
    { id: 5, passengerId: "p053", bid: 78, channel: "Email", time: "08:14" },
    { id: 6, passengerId: "p054", bid: 60, channel: "App", time: "09:25" },
    { id: 7, passengerId: "p055", bid: 45, channel: "MMB", time: "10:50" },
  ]),
  ...exitRowBids("HY 177", [
    { id: 4, passengerId: "p056", bid: 75, channel: "Web", time: "07:20" },
    { id: 5, passengerId: "p057", bid: 55, channel: "App", time: "08:42" },
    { id: 6, passengerId: "p058", bid: 40, channel: "Email", time: "10:05" },
  ]),
  ...exitRowBids("HY 551", [
    { id: 6, passengerId: "p059", bid: 72, channel: "App", time: "06:55" },
    { id: 7, passengerId: "p060", bid: 58, channel: "Web", time: "08:17" },
    { id: 8, passengerId: "p061", bid: 42, channel: "MMB", time: "09:30" },
  ]),
  ...exitRowBids("HY 409", [
    { id: 5, passengerId: "p062", bid: 70, channel: "Email", time: "11:08" },
    { id: 6, passengerId: "p063", bid: 55, channel: "App", time: "12:22" },
    { id: 7, passengerId: "p064", bid: 38, channel: "Web", time: "13:45" },
  ]),
  ...exitRowBids("HY 088", [
    { id: 3, passengerId: "p065", bid: 68, channel: "MMB", time: "14:30" },
    { id: 4, passengerId: "p066", bid: 52, channel: "App", time: "15:12" },
    { id: 5, passengerId: "p067", bid: 36, channel: "Web", time: "16:00" },
  ]),
  ...exitRowBids("HY 312", [
    { id: 4, passengerId: "p068", bid: 74, channel: "Email", time: "13:18" },
    { id: 5, passengerId: "p069", bid: 50, channel: "App", time: "14:40" },
    { id: 6, passengerId: "p070", bid: 34, channel: "Web", time: "15:55" },
  ]),
];
