import { T } from "./theme";
import type {
  Airport,
  Bid,
  BidState,
  Channel,
  City,
  Country,
  Flight,
  FlightHaul,
  FlightStatus,
  Rules,
  SeatCell,
  Tier,
} from "./types";

export const COUNTRIES_DATA: Country[] = [
  { id: "uz", name: { en: "Uzbekistan", ru: "Узбекистан" } },
  { id: "tr", name: { en: "Turkey", ru: "Турция" } },
  { id: "ae", name: { en: "United Arab Emirates", ru: "ОАЭ" } },
  { id: "ru", name: { en: "Russia", ru: "Россия" } },
  { id: "de", name: { en: "Germany", ru: "Германия" } },
  { id: "cn", name: { en: "China", ru: "Китай" } },
  { id: "kr", name: { en: "South Korea", ru: "Южная Корея" } },
  { id: "gb", name: { en: "United Kingdom", ru: "Великобритания" } },
  { id: "kz", name: { en: "Kazakhstan", ru: "Казахстан" } },
];

export const CITIES_DATA: City[] = [
  {
    id: "tashkent",
    name: { en: "Tashkent", ru: "Ташкент" },
    countryId: "uz",
    timezone: "Asia/Tashkent",
  },
  {
    id: "istanbul",
    name: { en: "Istanbul", ru: "Стамбул" },
    countryId: "tr",
    timezone: "Europe/Istanbul",
  },
  { id: "dubai", name: { en: "Dubai", ru: "Дубай" }, countryId: "ae", timezone: "Asia/Dubai" },
  {
    id: "moscow",
    name: { en: "Moscow", ru: "Москва" },
    countryId: "ru",
    timezone: "Europe/Moscow",
  },
  {
    id: "frankfurt",
    name: { en: "Frankfurt", ru: "Франкфурт" },
    countryId: "de",
    timezone: "Europe/Berlin",
  },
  {
    id: "beijing",
    name: { en: "Beijing", ru: "Пекин" },
    countryId: "cn",
    timezone: "Asia/Shanghai",
  },
  { id: "seoul", name: { en: "Seoul", ru: "Сеул" }, countryId: "kr", timezone: "Asia/Seoul" },
  {
    id: "london",
    name: { en: "London", ru: "Лондон" },
    countryId: "gb",
    timezone: "Europe/London",
  },
  {
    id: "almaty",
    name: { en: "Almaty", ru: "Алматы" },
    countryId: "kz",
    timezone: "Asia/Almaty",
  },
];

export const AIRPORTS_DATA: Airport[] = [
  {
    id: "TAS",
    name: { en: "Tashkent International Airport", ru: "Международный аэропорт Ташкент" },
    cityId: "tashkent",
  },
  {
    id: "IST",
    name: { en: "Istanbul Airport", ru: "Аэропорт Стамбул" },
    cityId: "istanbul",
  },
  {
    id: "DXB",
    name: { en: "Dubai International Airport", ru: "Международный аэропорт Дубай" },
    cityId: "dubai",
  },
  {
    id: "MOW",
    name: { en: "Moscow Sheremetyevo Airport", ru: "Шереметьево" },
    cityId: "moscow",
  },
  {
    id: "FRA",
    name: { en: "Frankfurt Airport", ru: "Аэропорт Франкфурт" },
    cityId: "frankfurt",
  },
  {
    id: "PEK",
    name: { en: "Beijing Capital International Airport", ru: "Пекин Столичный" },
    cityId: "beijing",
  },
  {
    id: "ICN",
    name: { en: "Incheon International Airport", ru: "Аэропорт Инчхон" },
    cityId: "seoul",
  },
  {
    id: "LHR",
    name: { en: "London Heathrow Airport", ru: "Хитроу" },
    cityId: "london",
  },
  {
    id: "ALA",
    name: { en: "Almaty International Airport", ru: "Международный аэропорт Алматы" },
    cityId: "almaty",
  },
];

export const FLIGHTS_DATA: Flight[] = [
  {
    id: "HY 602",
    fromAirportId: "TAS",
    toAirportId: "IST",
    depAt: "2026-06-15T08:45:00Z",
    arrAt: "2026-06-15T14:20:00Z",
    aircraft: "A321",
    bcFree: 2,
    bcTotal: 16,
    status: "active",
    haul: "medium",
  },
  {
    id: "HY 814",
    fromAirportId: "TAS",
    toAirportId: "DXB",
    depAt: "2026-06-15T14:30:00Z",
    arrAt: "2026-06-15T19:15:00Z",
    aircraft: "B787",
    bcFree: 8,
    bcTotal: 24,
    status: "active",
    haul: "medium",
  },
  {
    id: "HY 233",
    fromAirportId: "TAS",
    toAirportId: "MOW",
    depAt: "2026-06-15T11:15:00Z",
    arrAt: "2026-06-15T14:30:00Z",
    aircraft: "A320",
    bcFree: 0,
    bcTotal: 8,
    status: "sold",
    haul: "short",
  },
  {
    id: "HY 177",
    fromAirportId: "TAS",
    toAirportId: "FRA",
    depAt: "2026-06-16T06:00:00Z",
    arrAt: "2026-06-16T13:45:00Z",
    aircraft: "B767",
    bcFree: 14,
    bcTotal: 20,
    status: "upcoming",
    haul: "long",
  },
  {
    id: "HY 409",
    fromAirportId: "TAS",
    toAirportId: "PEK",
    depAt: "2026-06-16T09:20:00Z",
    arrAt: "2026-06-16T14:50:00Z",
    aircraft: "A330",
    bcFree: 6,
    bcTotal: 18,
    status: "active",
    haul: "medium",
  },
  {
    id: "HY 551",
    fromAirportId: "TAS",
    toAirportId: "ICN",
    depAt: "2026-06-16T13:00:00Z",
    arrAt: "2026-06-16T19:15:00Z",
    aircraft: "B787",
    bcFree: 3,
    bcTotal: 20,
    status: "active",
    haul: "long",
  },
  {
    id: "HY 088",
    fromAirportId: "TAS",
    toAirportId: "LHR",
    depAt: "2026-06-17T00:30:00Z",
    arrAt: "2026-06-17T09:20:00Z",
    aircraft: "B767",
    bcFree: 10,
    bcTotal: 16,
    status: "upcoming",
    haul: "ultra",
  },
  {
    id: "HY 312",
    fromAirportId: "TAS",
    toAirportId: "ALA",
    depAt: "2026-06-15T16:45:00Z",
    arrAt: "2026-06-15T17:50:00Z",
    aircraft: "A319",
    bcFree: 4,
    bcTotal: 8,
    status: "active",
    haul: "ultra-short",
  },
];

// Hand-authored seed. HY 602 keeps the curated 10 bids that drive the detail UI and
// auto-select tests (top weighted: id 1 = 682, id 4 = 580). Other flights get a small
// realistic spread so list-view aggregates aren't all zero.

type ExitRowSeed = {
  id: number;
  name: string;
  tier: Tier;
  bid: number;
  channel: Channel;
  time: string;
};

function exitRowBids(flightId: Flight["id"], rows: ExitRowSeed[]): Bid[] {
  return rows.map((r) => ({
    flightId,
    id: r.id,
    product: "exitRows",
    name: r.name,
    tier: r.tier,
    bid: r.bid,
    mult: 1.0,
    channel: r.channel,
    time: r.time,
    state: "pending",
  }));
}

export const SEED_BIDS: Bid[] = [
  // HY 602 (bcFree 2 — auto-select picks ids 1 and 4)
  {
    flightId: "HY 602",
    id: 1,
    product: "businessClass",
    name: "Иванов А.П.",
    tier: "Platinum",
    bid: 620,
    mult: 1.1,
    channel: "Email",
    time: "09:14",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 2,
    product: "businessClass",
    name: "Ли Вэй",
    tier: "Gold",
    bid: 520,
    mult: 1.05,
    channel: "App",
    time: "13:07",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 3,
    product: "businessClass",
    name: "Петрова М.С.",
    tier: "Silver",
    bid: 490,
    mult: 1.03,
    channel: "Email",
    time: "10:21",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 4,
    product: "businessClass",
    name: "Smith J.",
    tier: "Standard",
    bid: 580,
    mult: 1.0,
    channel: "MMB",
    time: "11:32",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 5,
    product: "businessClass",
    name: "Karimov B.",
    tier: "Platinum",
    bid: 400,
    mult: 1.1,
    channel: "Web",
    time: "08:55",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 6,
    product: "businessClass",
    name: "Ahmadov F.",
    tier: "Standard",
    bid: 470,
    mult: 1.0,
    channel: "Email",
    time: "14:45",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 7,
    product: "businessClass",
    name: "Brown T.",
    tier: "Gold",
    bid: 380,
    mult: 1.05,
    channel: "MMB",
    time: "07:30",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 8,
    product: "businessClass",
    name: "Назаров О.",
    tier: "Standard",
    bid: 310,
    mult: 1.0,
    channel: "Web",
    time: "16:02",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 9,
    product: "businessClass",
    name: "Юсупова Д.",
    tier: "Silver",
    bid: 345,
    mult: 1.03,
    channel: "Email",
    time: "15:18",
    state: "pending",
  },
  {
    flightId: "HY 602",
    id: 10,
    product: "businessClass",
    name: "Kim S.",
    tier: "Gold",
    bid: 430,
    mult: 1.05,
    channel: "App",
    time: "12:00",
    state: "pending",
  },

  // HY 814
  {
    flightId: "HY 814",
    id: 1,
    product: "businessClass",
    name: "Tan W.",
    tier: "Gold",
    bid: 480,
    mult: 1.05,
    channel: "App",
    time: "09:20",
    state: "pending",
  },
  {
    flightId: "HY 814",
    id: 2,
    product: "businessClass",
    name: "Орлов И.",
    tier: "Standard",
    bid: 410,
    mult: 1.0,
    channel: "Web",
    time: "10:05",
    state: "pending",
  },
  {
    flightId: "HY 814",
    id: 3,
    product: "businessClass",
    name: "Patel R.",
    tier: "Silver",
    bid: 360,
    mult: 1.03,
    channel: "Email",
    time: "11:40",
    state: "pending",
  },
  {
    flightId: "HY 814",
    id: 4,
    product: "businessClass",
    name: "Khan A.",
    tier: "Standard",
    bid: 300,
    mult: 1.0,
    channel: "MMB",
    time: "13:12",
    state: "pending",
  },

  // HY 233 (sold)
  {
    flightId: "HY 233",
    id: 1,
    product: "businessClass",
    name: "Соколов В.",
    tier: "Platinum",
    bid: 390,
    mult: 1.1,
    channel: "Email",
    time: "07:45",
    state: "pending",
  },
  {
    flightId: "HY 233",
    id: 2,
    product: "businessClass",
    name: "Юлдашев Б.",
    tier: "Gold",
    bid: 350,
    mult: 1.05,
    channel: "App",
    time: "08:10",
    state: "pending",
  },
  {
    flightId: "HY 233",
    id: 3,
    product: "businessClass",
    name: "Ким Д.",
    tier: "Standard",
    bid: 280,
    mult: 1.0,
    channel: "Web",
    time: "09:30",
    state: "pending",
  },
  {
    flightId: "HY 233",
    id: 4,
    product: "businessClass",
    name: "Морозова Е.",
    tier: "Silver",
    bid: 260,
    mult: 1.03,
    channel: "Email",
    time: "10:15",
    state: "pending",
  },

  // HY 177
  {
    flightId: "HY 177",
    id: 1,
    product: "businessClass",
    name: "Müller K.",
    tier: "Gold",
    bid: 550,
    mult: 1.05,
    channel: "App",
    time: "06:20",
    state: "pending",
  },
  {
    flightId: "HY 177",
    id: 2,
    product: "businessClass",
    name: "Schmidt L.",
    tier: "Standard",
    bid: 480,
    mult: 1.0,
    channel: "Web",
    time: "07:50",
    state: "pending",
  },
  {
    flightId: "HY 177",
    id: 3,
    product: "businessClass",
    name: "Усманов Р.",
    tier: "Silver",
    bid: 420,
    mult: 1.03,
    channel: "Email",
    time: "09:00",
    state: "pending",
  },

  // HY 409
  {
    flightId: "HY 409",
    id: 1,
    product: "businessClass",
    name: "Wang J.",
    tier: "Platinum",
    bid: 510,
    mult: 1.1,
    channel: "App",
    time: "08:00",
    state: "pending",
  },
  {
    flightId: "HY 409",
    id: 2,
    product: "businessClass",
    name: "Liu Y.",
    tier: "Gold",
    bid: 460,
    mult: 1.05,
    channel: "Email",
    time: "08:35",
    state: "pending",
  },
  {
    flightId: "HY 409",
    id: 3,
    product: "businessClass",
    name: "Zhang H.",
    tier: "Standard",
    bid: 380,
    mult: 1.0,
    channel: "MMB",
    time: "09:15",
    state: "pending",
  },
  {
    flightId: "HY 409",
    id: 4,
    product: "businessClass",
    name: "Chen X.",
    tier: "Silver",
    bid: 340,
    mult: 1.03,
    channel: "Web",
    time: "10:00",
    state: "pending",
  },

  // HY 551
  {
    flightId: "HY 551",
    id: 1,
    product: "businessClass",
    name: "Park J.",
    tier: "Gold",
    bid: 540,
    mult: 1.05,
    channel: "App",
    time: "11:00",
    state: "pending",
  },
  {
    flightId: "HY 551",
    id: 2,
    product: "businessClass",
    name: "Lee H.",
    tier: "Platinum",
    bid: 500,
    mult: 1.1,
    channel: "Email",
    time: "11:30",
    state: "pending",
  },
  {
    flightId: "HY 551",
    id: 3,
    product: "businessClass",
    name: "Choi S.",
    tier: "Standard",
    bid: 420,
    mult: 1.0,
    channel: "MMB",
    time: "12:10",
    state: "pending",
  },
  {
    flightId: "HY 551",
    id: 4,
    product: "businessClass",
    name: "Ким Н.",
    tier: "Silver",
    bid: 380,
    mult: 1.03,
    channel: "Web",
    time: "12:45",
    state: "pending",
  },
  {
    flightId: "HY 551",
    id: 5,
    product: "businessClass",
    name: "Yoon T.",
    tier: "Standard",
    bid: 320,
    mult: 1.0,
    channel: "App",
    time: "13:00",
    state: "pending",
  },

  // HY 088
  {
    flightId: "HY 088",
    id: 1,
    product: "businessClass",
    name: "Williams P.",
    tier: "Platinum",
    bid: 600,
    mult: 1.1,
    channel: "Email",
    time: "22:30",
    state: "pending",
  },
  {
    flightId: "HY 088",
    id: 2,
    product: "businessClass",
    name: "Davies M.",
    tier: "Gold",
    bid: 540,
    mult: 1.05,
    channel: "App",
    time: "23:10",
    state: "pending",
  },

  // HY 312 (ultra-short)
  {
    flightId: "HY 312",
    id: 1,
    product: "businessClass",
    name: "Aliev R.",
    tier: "Gold",
    bid: 95,
    mult: 1.05,
    channel: "App",
    time: "15:30",
    state: "pending",
  },
  {
    flightId: "HY 312",
    id: 2,
    product: "businessClass",
    name: "Назарбаев А.",
    tier: "Standard",
    bid: 80,
    mult: 1.0,
    channel: "Web",
    time: "16:00",
    state: "pending",
  },
  {
    flightId: "HY 312",
    id: 3,
    product: "businessClass",
    name: "Tolegen B.",
    tier: "Silver",
    bid: 70,
    mult: 1.03,
    channel: "Email",
    time: "16:15",
    state: "pending",
  },
  // ---- Exit-row bids ($32–$85) ----
  // HY 602 (14 — drives the detail page chart)
  ...exitRowBids("HY 602", [
    { id: 11, name: "Khan A.", tier: "Gold", bid: 82, channel: "App", time: "07:42" },
    { id: 12, name: "Park J.", tier: "Standard", bid: 78, channel: "Web", time: "08:11" },
    { id: 13, name: "Орлов В.", tier: "Silver", bid: 75, channel: "Email", time: "09:03" },
    { id: 14, name: "Müller K.", tier: "Standard", bid: 72, channel: "MMB", time: "09:48" },
    { id: 15, name: "Сидорова Е.", tier: "Gold", bid: 68, channel: "App", time: "10:30" },
    { id: 16, name: "Tanaka R.", tier: "Standard", bid: 64, channel: "Web", time: "11:05" },
    { id: 17, name: "Назаров Б.", tier: "Silver", bid: 62, channel: "Email", time: "11:42" },
    { id: 18, name: "Garcia L.", tier: "Standard", bid: 60, channel: "App", time: "12:15" },
    { id: 19, name: "Choi H.", tier: "Standard", bid: 58, channel: "MMB", time: "13:00" },
    { id: 20, name: "Романов И.", tier: "Silver", bid: 52, channel: "Web", time: "13:38" },
    { id: 21, name: "Fischer T.", tier: "Standard", bid: 48, channel: "App", time: "14:20" },
    { id: 22, name: "Алиев Р.", tier: "Standard", bid: 42, channel: "Email", time: "15:05" },
    { id: 23, name: "Singh P.", tier: "Standard", bid: 38, channel: "Web", time: "15:44" },
    { id: 24, name: "Чен Ю.", tier: "Standard", bid: 32, channel: "MMB", time: "16:22" },
  ]),
  ...exitRowBids("HY 814", [
    { id: 5, name: "Ким А.", tier: "Gold", bid: 80, channel: "App", time: "10:11" },
    { id: 6, name: "Brown D.", tier: "Standard", bid: 65, channel: "Web", time: "11:48" },
    { id: 7, name: "Юлдашев Б.", tier: "Silver", bid: 50, channel: "Email", time: "12:30" },
  ]),
  ...exitRowBids("HY 233", [
    { id: 5, name: "Назарова Г.", tier: "Gold", bid: 78, channel: "Email", time: "08:14" },
    { id: 6, name: "Iqbal S.", tier: "Standard", bid: 60, channel: "App", time: "09:25" },
    { id: 7, name: "Каримова З.", tier: "Standard", bid: 45, channel: "MMB", time: "10:50" },
  ]),
  ...exitRowBids("HY 177", [
    { id: 4, name: "Rahimi K.", tier: "Silver", bid: 75, channel: "Web", time: "07:20" },
    { id: 5, name: "Соколов Д.", tier: "Standard", bid: 55, channel: "App", time: "08:42" },
    { id: 6, name: "Yamamoto T.", tier: "Standard", bid: 40, channel: "Email", time: "10:05" },
  ]),
  ...exitRowBids("HY 551", [
    { id: 6, name: "Эргашев А.", tier: "Gold", bid: 72, channel: "App", time: "06:55" },
    { id: 7, name: "Lopez M.", tier: "Standard", bid: 58, channel: "Web", time: "08:17" },
    { id: 8, name: "Тимуров К.", tier: "Standard", bid: 42, channel: "MMB", time: "09:30" },
  ]),
  ...exitRowBids("HY 409", [
    { id: 5, name: "Wang L.", tier: "Silver", bid: 70, channel: "Email", time: "11:08" },
    { id: 6, name: "Захаров П.", tier: "Standard", bid: 55, channel: "App", time: "12:22" },
    { id: 7, name: "Ahmed F.", tier: "Standard", bid: 38, channel: "Web", time: "13:45" },
  ]),
  ...exitRowBids("HY 088", [
    { id: 3, name: "Юсупов Т.", tier: "Gold", bid: 68, channel: "MMB", time: "14:30" },
    { id: 4, name: "Novak J.", tier: "Standard", bid: 52, channel: "App", time: "15:12" },
    { id: 5, name: "Габидуллина М.", tier: "Standard", bid: 36, channel: "Web", time: "16:00" },
  ]),
  ...exitRowBids("HY 312", [
    { id: 4, name: "Bekov S.", tier: "Silver", bid: 74, channel: "Email", time: "13:18" },
    { id: 5, name: "Petrov K.", tier: "Standard", bid: 50, channel: "App", time: "14:40" },
    { id: 6, name: "Хасанов Н.", tier: "Standard", bid: 34, channel: "Web", time: "15:55" },
  ]),
];

export const SEAT_MAP_BC: Array<Array<SeatCell | null>> = [
  [
    { id: "1A", taken: true },
    { id: "1C", taken: true },
    null,
    { id: "1D", taken: true },
    { id: "1F", taken: true },
  ],
  [
    { id: "2A", taken: true },
    { id: "2C", taken: true },
    null,
    { id: "2D", taken: true },
    { id: "2F", taken: true },
  ],
  [
    { id: "3A", taken: true },
    { id: "3C", taken: true },
    null,
    { id: "3D", taken: true },
    { id: "3F", taken: true },
  ],
  [
    { id: "4A", taken: false, bid: true },
    { id: "4C", taken: true },
    null,
    { id: "4D", taken: true },
    { id: "4F", taken: false, bid: true },
  ],
];

export const DEFAULT_RULES: Rules = {
  inviteDaysBefore: 14,
  chaserHoursBefore: 48,
  closureHoursBefore: 4,
  autoFulfillment: true,
  requirePurchased: true,
  blindBids: true,
  maxUpgradesPerFlight: 0,
  multiplierPlatinum: 10,
  multiplierGold: 5,
  multiplierSilver: 3,
  minBcUltraShort: 93,
  minBcShort: 118,
  minBcMedium: 262,
  minBcLong: 500,
  minBcUltraLong: 569,
  minExitShort: 8,
  minExitMedium: 32,
  minExitLong: 35,
  minSeatBlockShort: 8,
  minSeatBlockMedium: 32,
  minSeatBlockLong: 35,
  channels: { email: true, mmb: true, app: true, web: true, webcheckin: true, pushNotif: true },
  paymentMethods: { visa: true, mastercard: true, amex: true, jcb: false, diners: false },
  use3ds: false,
  continuousPricing: true,
  crossAirlineUpgrades: false,
  payWithPoints: false,
  seatBlocker: true,
};

export const weighted = (b: Bid) => Math.round(b.bid * b.mult);

export type ColorTokenId = keyof typeof T;

export const colorToken = (id: ColorTokenId): string => T[id];

export const TIER_META: Record<
  Tier,
  { colorId: ColorTokenId; bgId: ColorTokenId; label: string; mult: string }
> = {
  Platinum: {
    colorId: "statusWarning",
    bgId: "statusWarningBg",
    label: "Platinum",
    mult: "+10%",
  },
  Gold: {
    colorId: "brandPrimary",
    bgId: "brandPrimaryBg",
    label: "Gold",
    mult: "+5%",
  },
  Silver: {
    colorId: "textSecondary",
    bgId: "neutralBgSoft",
    label: "Silver",
    mult: "+3%",
  },
  Standard: {
    colorId: "textMuted",
    bgId: "neutralBgPale",
    label: "Standard",
    mult: "—",
  },
};

export const STATE_META: Record<
  BidState,
  { label: string; colorId: ColorTokenId; bgId: ColorTokenId }
> = {
  pending: { label: "Ожидает", colorId: "textMuted", bgId: "neutralBgSoft" },
  approved: {
    label: "Принята",
    colorId: "statusSuccessFg",
    bgId: "statusSuccessBg",
  },
  rejected: {
    label: "Отклонена",
    colorId: "statusDangerFg",
    bgId: "statusDangerBg",
  },
};

export const STATUS_META: Record<
  FlightStatus,
  { label: string; colorId: ColorTokenId; bgId: ColorTokenId }
> = {
  active: {
    label: "Активен",
    colorId: "statusSuccessFg",
    bgId: "statusSuccessBg",
  },
  sold: { label: "Нет мест", colorId: "statusDangerFg", bgId: "statusDangerBg" },
  upcoming: {
    label: "Скоро",
    colorId: "statusWarningFg",
    bgId: "statusWarningBg",
  },
};

export const HAUL_LABELS: Record<FlightHaul, string> = {
  "ultra-short": "Ультракороткий (<1.5ч)",
  short: "Короткий (1.5–3ч)",
  medium: "Средний (3–5ч)",
  long: "Длинный (5–8ч)",
  ultra: "Ультрадальний (8ч+)",
};

export const CH_ICONS: Record<Channel, string> = {
  Email: "✉",
  App: "◉",
  MMB: "⊞",
  Web: "◈",
};
